layout: sidebar
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: stars
#  sort_by options:
#     - pushed
#     - stars
  limit: 6
  exclude:
    archived: false
    forks: true
    projects:
     - AMS

skills:
  - name: Java (up to 8)
    web_url: https://github.com/topics/java
    image_url: assets/java.jpg
    
  - name: Spring Framework
    web_url: https://github.com/topics/spring-boot
    image_url: assets/spring.png
    
  - name: APIs, Application & Data Integration, Middleware
    web_url: https://github.com/topics/api
    image_url: assets/api.png
    
  - name: Python & Ruby Scripting
    web_url: https://github.com/topics/scripting
    image_url: assets/python.png

  - name: SQL & NoSQL Databases
    web_url: https://github.com/topics/database
    image_url: assets/databases.png

  - name: JSON, XML and HTML Parsing
    web_url: https://github.com/topics/xml
    image_url: assets/parsing.png

     
social_media:
  # behance: your_username
  # dribbble: your_username
  # facebook: your_username
  # hackerrank: your_username
  # instagram: your_username
  # keybase: your_username
   linkedin: henrique-caldeira-b416b5ab
  # mastodon: your_username
  # medium: your_username
  # stackoverflow: your_user_id
  # telegram: your_username
  # twitter: your_username
  # unsplash: your_username
  # vk: your_username
  # website: http://your_website_url
  # youtube: your_username

topics:
  - name: AWS Development
    web_url: https://github.com/topics/aws
    image_url: assets/aws.png
    
  - name: Continuous Integration
    web_url: https://github.com/topics/continuous-integration
    image_url: assets/continuous-integration.png
    
  - name: Code Quality & Design Patterns
    web_url: https://github.com/topics/code-quality
    image_url: assets/code-quality.png
    
  - name: Blockchain
    web_url: https://github.com/topics/blockchain
    image_url: assets/blockchain.jpg

  - name: Cryptocurrencies
    web_url: https://github.com/topics/cryptocurrency
    image_url: assets/cryptocurrency.png

  - name: Go (language)
    web_url: https://github.com/topics/go
    image_url: assets/go.png
