layout: sidebar
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: stars
#  sort_by options:
#     - pushed
#     - stars
  limit: 6
  exclude:
    archived: false
    forks: true
    projects:
     - AMS

social_media:
  # behance: your_username
  # dribbble: your_username
  # facebook: your_username
  # hackerrank: your_username
  # instagram: your_username
  # keybase: your_username
   linkedin: henrique-caldeira-b416b5ab
  # mastodon: your_username
  # medium: your_username
  # stackoverflow: your_user_id
  # telegram: your_username
  # twitter: your_username
  # unsplash: your_username
  # vk: your_username
  # website: http://your_website_url
  # youtube: your_username

topics:
  - name: AWS
    web_url: https://github.com/topics/aws
    image_url: assets/aws.png

  - name: Blockchain
    web_url: https://github.com/topics/blockchain
    image_url: assets/blockchain.jpg

  - name: Code Quality & Design Patterns
    web_url: https://github.com/topics/code-quality
    image_url: assets/code-quality.png

  - name: Continuous Integration
    web_url: https://github.com/topics/continuous-integration
    image_url: assets/continuous-integration.png

  - name: Cryptocurrency
    web_url: https://github.com/topics/cryptocurrency
    image_url: assets/cryptocurrency.png

  - name: Go (language)
    web_url: https://github.com/topics/go
    image_url: assets/go.png
